apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ include "gitMirror.name" . }}-metrics
    helm.sh/chart: {{ include "gitMirror.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "gitMirror.name" . }}-metrics
spec:
  replicas: {{ .Values.metrics.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gitMirror.name" . }}-metrics
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gitMirror.name" . }}-metrics
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      shareProcessNamespace: true
      containers:
      - name: metrics
        env:
        - name: INFLUX_USER
          valueFrom:
            secretKeyRef:
              name: metrics
              key: INFLUX_USER
        - name: INFLUX_PASS
          valueFrom:
            secretKeyRef:
              name: metrics
              key: INFLUX_PASS
        - name: INFLUX_URL
          valueFrom:
            secretKeyRef:
              name: metrics
              key: INFLUX_URL
        args:
        - rancher-catalog-stats
        - -filepath
        - \"/var/log/nginx/access-*.log\"
        - -influxurl
        - $(INFLUX_URL)
        - -influxdb
        - catalog
        - -daemon
        - -poll
        - -influxuser
        - $(INFLUX_USER)
        - -influxpass
        - $(INFLUX_PASS)
        image: {{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
        resources:
          {{ toYaml .Values.metrics.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/log/nginx
          name: efs-shared
      restartPolicy: Always

      volumes:
      - name: efs-shared
        persistentVolumeClaim:
          claimName: efs-shared
