apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ include "gitMirror.name" . }}-mirror
    helm.sh/chart: {{ include "gitMirror.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "gitMirror.name" . }}-mirror
spec:
  replicas: {{ .Values.mirror.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gitMirror.name" . }}-mirror
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gitMirror.name" . }}-mirror
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      shareProcessNamespace: true
      containers:
      - name: mirror
        env:
        - name: MIRROR_DATA_DIR
          value: {{ .Values.mirrorDataDir }}
        - name: MIRROR_DEBUG
          value: "{{ .Values.mirrorDebug }}"
        - name: MIRROR_ETCD_ENDPOINTS
          value: {{ .Values.mirrorEtcdEndpoints }}
        - name: MIRROR_GITHUB_LISTEN_ADDR
          value: {{ .Values.mirrorGithubListenAddr }}
        - name: MIRROR_POLL_PERIOD
          value: {{ .Values.mirrorPollPeriod }}
        - name: MIRROR_REPO
          value: {{ .Values.mirrorRepo }}
        image: {{ .Values.mirror.image.repository }}:{{ .Values.mirror.image.tag }}
        imagePullPolicy: {{ .Values.mirror.image.pullPolicy }}
        resources:
          {{ toYaml .Values.mirror.resources | nindent 10 }}
        volumeMounts:
        - mountPath: {{ .Values.mirrorDataDir }}
          name: git-dir
      - name: serve
        env:
        - name: SERVER_NAME
          value: {{ .Values.serverName }}
        - name: WORKER_CONNECTIONS
          value: "{{ .Values.workerConnections }}"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: {{ .Values.serve.image.repository }}:{{ .Values.serve.image.tag }}
        imagePullPolicy: {{ .Values.serve.image.pullPolicy }}
        resources:
          {{ toYaml .Values.serve.resources | nindent 10 }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: {{ .Values.mirrorDataDir }}
          name: git-dir
      - name: logrotate
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CATALOG_FILEPATH
          value: {{ .Values.catalog_filepath }}
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
        image: {{ .Values.logrotate.image.repository }}:{{ .Values.logrotate.image.tag }}
        imagePullPolicy: {{ .Values.logrotate.image.pullPolicy }}
        resources:
          {{ toYaml .Values.logrotate.resources | nindent 10 }}
        volumeMounts:
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 8 }}
{{- end }}
      restartPolicy: Always
      volumes:
      - name: git-dir
        emptyDir:
          medium: Memory
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 8 }}
{{- end }}