mirror:
  replicaCount: 3
  image:
    repository: rancher/git-mirror
    tag: v0.3.1
    pullPolicy: IfNotPresent
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi

serve:
  image:
    repository: rancher/git-serve
    tag: v0.3.1
    pullPolicy: IfNotPresent
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      prometheus.io/scrape: "true"
      prometheus.io/port: "10254"
      nginx.ingress.kubernetes.io/ssl-ciphers: "HIGH:!aNULL:!MD5"
    path: /
    hosts:
      - git.rancher.io
    tls:
     - secretName: git-rancher-io-tls
       hosts:
         - git.rancher.io

logrotate:
  image:
    repository: rancher/git-logrotate
    tag: v0.3.1
    pullPolicy: IfNotPresent
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi

analyze:
  enabled: false
  replicaCount: 1
  image:
    repository: rancher/git-analyze
    tag: v0.3.1
    pullPolicy: IfNotPresent
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi

metrics:
  replicaCount: 1
  image:
    repository: rawmind/rancher-catalog-stats
    tag: 0.3-1
    pullPolicy: IfNotPresent
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi

nameOverride: ""
fullnameOverride: ""

mirrorDataDir: /var/git
mirrorDebug: "false"
mirrorEtcdEndpoints: http://etcd:2379
mirrorGithubListenAddr: :4141
mirrorPollPeriod: 5m
mirrorRepo: https://github.com/rancher/rancher-catalog, https://github.com/rancher/community-catalog, https://github.com/rancher/infra-catalog, https://github.com/rancher/charts,https://github.com/rancher/system-charts
serverName: git.rancher.io
workerConnections: 4096

nodeSelector: {}

tolerations: []

affinity: {}
