apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "rdnsserver.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "rdnsserver.name" . }}
    spec:
      containers:
        - name: {{ template "rdnsserver.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: AWS_HOSTED_ZONE_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: awsHostedZoneId
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: awsAccessKeyId
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: awsSecretAccessKey
          - name: DSN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: dsn
          - name: TTL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: ttl
          args:
          - route53
          ports:
            - name: http
              containerPort: 9333
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            # Allow chart users to specify resources. Usually, no default should
            # be set, so this is left to be a conscious choice to the chart
            # users and avoids that charts don't run out of the box on, e. g.,
            # Minikube when high resource requests are specified by default.
            {{- toYaml .Values.resources | nindent 12 }}
          annotations:
            {{- toYaml .Values.podAnnotations| nindent 12 }}
